name: Update README with Date
description: Set the update date and update README.md with it

runs:
  using: "composite"
  steps:
    - name: Set update date variable
      shell: bash
      run: |
        UPDATE_DATE=$(date)
        echo "UPDATE_DATE=${UPDATE_DATE}" >> $GITHUB_ENV

    - name: Update last sync date in README.md
      shell: bash
      env:
        BEGIN_TAG: "<!-- BEGIN SYNC INFO -->"
        END_TAG: "<!-- END SYNC INFO -->"
      run: |
        UPDATE=$(cat README.md | perl -0777 -pe 's#($BEGIN_TAG)(?:.|\n)*?($END_TAG)#${1}\nLast sync to launchpad: $UPDATE_DATE\n${2}#g')
        echo "${UPDATE}" > README.md

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "bump timestamp"
        default_author: github_actions

