name: automation
on:
  workflow_dispatch:
  # Run daily at 11:45 UTC.
  schedule:
    - cron: '45 11 * * *'

jobs:
  # Updates the timestamp in README.md, which triggers a "push" event.
  bump_timestamp:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: nightly
      - name: update-readme
        uses: ./.github/actions/timestamp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

